FROM ig-image
# COPY config/routes/hello.json "$IG_INSTANCE_DIR"/config/routes/hello.json
COPY config/. "$IG_INSTANCE_DIR"/config/
# COPY startup.sh /opt/startup.sh
# RUN chmod +x /opt/startup.sh
# ENTRYPOINT ["/opt/startup.sh"]