replicaCount: 1

image:
  repository: pingidentity/pinggateway
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  hostname: default.ds.example.com
  tls:
    enabled: true
    secretName: ping-local-ds-tls