# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ping-gateway
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: ping-gateway
